### ISSUE TITLE
Update make-config-files.sh to be less interactive

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#23]
Try and log in to Azure in `make-config-files.sh` with a Service Principal so a user doesn't have to interact with a webpage. This is work towards [HelmUpgradeBot/hub23-deploy-upgrades](https://github.com/HelmUpgradeBot/hub23-deploy-upgrades) which will hopefully run helm chart upgrades automatically so I don't have to 😄 

First hurdle: How do we keep a local copy of SP client ID and key? Can't pull them from the key-vault without logging into Azure, can't (non-interactively) log into Azure without them!

Then: SP Client ID and key such be parsed to the HelmUpgradeBot script as environment variables, like the PAT. We can then use the SP to log in to Azure, pull relevant secrets to build the config files, pull the k8s cluster credentials and then upgrade the helm chart deployment.

@jemrobinson any ideas on this?

**Comment by martintoreilly** [comment]
I'd look into running this as an Azure function app and granting the "system managed identity" of the app rights to do what is needed. For actions on Azure, I think the app would no longer need access to Service Principal credentials. This app could then be deployed with interactive log in from an authorised person.

**Comment by sgibson91** [comment]
So I have been looking at Azure function apps as I'd like the bot I'm writing to check for new Helm Charts released [here](https://jupyterhub.github.io/helm-chart/#development-releases-binderhub), say, once a day. Would an authorised user have to log in once a day, or only when the function is deployed?
