### ISSUE TITLE
[BUG] Lint and Validate workflow is broken

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#336]
**Describe the bug**

The lint and validate CI workflow is currently broken and I'm not sure why.

`helm lint` executes fine locally, e.g.:

```
$ pwd                        
/Users/sgibson/source/github/alan-turing-institute/hub23-deploy

$ ls          
CODE_OF_CONDUCT.md   LICENSE              billing              deploy               docs                 pyproject.toml       templates
CONTRIBUTING.md      README.md            cli-tool             dev-requirements.txt hub23-chart          static               yamllint-config.yaml

$ ls deploy/               
cert-manager.yaml  prod-template.yaml prod.yaml          test-values.yaml

$ helm lint hub23-chart -f deploy/prod.yaml -f deploy/test-values.yaml -f hub23-chart/values.yaml
==> Linting hub23-chart
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

**To Reproduce**

Run any CI job and see the logs, e.g. [here](https://github.com/alan-turing-institute/hub23-deploy/pull/339/checks?check_run_id=2012802479)

**Expected behaviour**

`helm lint` run in CI would pass as it does locally

**Screenshots**

**Additional context**

CI configuration can be found [here](https://github.com/alan-turing-institute/hub23-deploy/blob/d57f7c5f00a66cf3992543de53266f770915c4dd/.github/workflows/lint-format.yml#L54-L106)

Local version of helm: `helm version --short: v3.5.2+g167aac7`
[Version of helm installed in CI](https://github.com/alan-turing-institute/hub23-deploy/blob/d57f7c5f00a66cf3992543de53266f770915c4dd/.github/workflows/lint-format.yml#L64)

(Tried to) Address the authentication config change [here](https://github.com/alan-turing-institute/hub23-deploy/pull/335)

**Comment by sgibson91** [comment]
@consideRatio I don't know if you have any insight into why `helm lint` would pass locally but not in CI?

**Comment by consideRatio** [comment]
@sgibson91 doing `helm lint` involves rendering templates. Rendering templates can include an explicit `fail` command and that triggers remotely while it doesn't do so locally. The difference relates to a difference of configuration passed.

This message here, is a message written to help with what kind of failure it is. The failure is that you are using a config that has been strictly deprecated still. Somehow `helm lint` end up given outdated chart configuration located under `auth`, but it should be moved to the suggested location under `hub.config` instead.

```
The JupyterHub Helm chart's auth config has been reworked and requires changes.

The new way to configure authentication in chart version 0.11.0+ is printed
below for your convenience. The values are not shown by default to ensure no
secrets are exposed, run helm upgrade with --set global.safeToShowValues=true
to show them.

hub:
  config:
    Authenticator:
      admin_users: '***'
    GitHubOAuthenticator:
      client_id: '***'
      client_secret: '***'
    JupyterHub:
      admin_access: '***'
      authenticator_class: <no value>
```

**Comment by sgibson91** [comment]
> ## Concrete fix
> Cleanup all configuration following the old configuration systems syntax where auth config were located under `auth`, and locate it like described in the error message.
> 
> Note that authenticator_class should be set to `"github"` (or a longer more explicit string).

I _thought_ I'd already implemented that fix in this PR? https://github.com/alan-turing-institute/hub23-deploy/pull/335

**Comment by consideRatio** [comment]
There are some traces remaining it seems: https://github.com/alan-turing-institute/hub23-deploy/search?q=auth%3A

**Comment by sgibson91** [comment]
I shall do another sweep 🙃 Thank you!

**Comment by consideRatio** [comment]
No worries! :) Happy to see things are kept updated!
