### ISSUE TITLE
GitHub pages to host docs folder

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#84]
Use jekyll and GitHub pages to host the documentation in `docs/`.

**Comment by sgibson91** [comment]
Useful links:

- https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/
- https://github.com/collections/github-pages-examples

**Comment by anirudhbagri** [comment]
Shouldn't it be done from repository settings?
Can you please elaborate little more, I would like to help

**Comment by sgibson91** [comment]
Yes gh-pages is enabled from the repository settings, but I was mostly thinking of the jekyll template and css files to generate pretty html. Or maybe a readthedocs style layout with proper pagination and cross-referencing. I was more reminding myself to pick a pretty theme than anything else 😂Thanks for dropping by though! ✨

**Comment by sgibson91** [comment]
Docs now deployed! ✨
