### ISSUE TITLE
Issues re-installing cert-manager 

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/hub23-deploy#91]
Error message:

```
Error: unable to recognize "": no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"
```

**Comment by sgibson91** [comment]
@consideRatio Are you aware of any recent changes in cert-manager that could cause this error? I'm still using v0.10.0 from when we initially set it up in Oslo.

**Comment by sgibson91** [comment]
I think it's the CRDs - sorry for the tag!

**Comment by consideRatio** [comment]
No worries, yepp this is the typical output of not having the CRDs available before installation of cert-manager. I'm not happy about the situation that we need to manually install these first =/ It makes it so much harder to create instructions to install z2jh depending on cert-manager.

**Comment by sgibson91** [comment]
Yeah, it's already been requested that they're included in the chart: https://github.com/jetstack/cert-manager/issues/2256

I've had to migrate Hub23, and re-installing cert-manager is an absolute nightmare! 😂I'll keep this open for the time being incase I come across any other issues.

**Comment by sgibson91** [comment]
I managed to set it up again! What we wrote [here](https://discourse.jupyter.org/t/wip-documentation-about-cert-manager/2068/2) has been a real lifesaver, as has relying on CI pipelines 😉

**Comment by consideRatio** [comment]
@sgibson91 haha excellent, I love it when documentation you have written yourself turn out to be useful to yourself to the extent that you are happy to have written it no matter if someone else end up benefiting from it! :D
